name: Run Tests

on:
  push:

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Linter (ktlint)
        run: ./gradlew ktlintFormat

      - name: Run Tests
        run: ./gradlew clean test
