name: Deploy App

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Gradle Tests
        run: ./gradlew clean test

      - name: Build, Push and Release a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          heroku_app_name: vegan-info
          email: gamebreak24@gmail.com
          heroku_api_key: a20208e3-0e93-40c3-9cb1-4570aeda19e3
